import 'package:can_23_teams/models/country.dart';

class MyDatas {
  static List<Country> teams = [
    Country(
        rang: 1,
        name: "Côte d’Ivoire",
        countryCode: "CI",
        description: "Qualifiée d'office en tant que pays hôte\n2e du groupe H",
        dateQualification: "8 janvier 2019",
        nbParticipation: 25,
        results: [1992, 2015],
        lastParticipation: "2021 (1/8 finale)",
        flag: "https://cdn-icons-png.flaticon.com/512/323/323347.png",
        topPlayer: "lien_photo_joueur_cote_divoire"),
    Country(
        rang: 2,
        name: "Maroc",
        countryCode: "MA",
        description: "1er du groupe K",
        dateQualification: "24 mars 2023",
        nbParticipation: 19,
        results: [1976],
        lastParticipation: "2021 (1/4 finale)",
        flag: "lien_drapeau_maroc",
        topPlayer: "lien_photo_joueur_maroc"),
    Country(
        rang: 3,
        name: "Algérie",
        countryCode: "DZ",
        description: "1er du groupe F",
        dateQualification: "27 mars 2023",
        nbParticipation: 20,
        results: [1990, 2019],
        lastParticipation: "2021 (1er tour)",
        flag: "lien_drapeau_algerie",
        topPlayer: "lien_photo_joueur_algerie"),
    Country(
        rang: 4,
        name: "Afrique du Sud",
        countryCode: "ZA",
        description: "2e du groupe K",
        dateQualification: "28 mars 2023",
        nbParticipation: 11,
        results: [1996],
        lastParticipation: "2019 (1/4 finale)",
        flag: "lien_drapeau_afrique_du_sud",
        topPlayer: "lien_photo_joueur_afrique_du_sud"),
    Country(
        rang: 5,
        name: "Sénégal",
        countryCode: "SN",
        description: "1er du groupe L",
        dateQualification: "28 mars 2023",
        nbParticipation: 17,
        results: [2021],
        lastParticipation: "2021 (Vainqueur)",
        flag: "lien_drapeau_senegal",
        topPlayer: "lien_photo_joueur_senegal"),
    Country(
        rang: 6,
        name: "Burkina Faso",
        countryCode: "BF",
        description: "1er du groupe B",
        dateQualification: "28 mars 2023",
        nbParticipation: 13,
        results: [],
        lastParticipation: "2021 (Quatrième)",
        flag: "lien_drapeau_burkina_faso",
        topPlayer: "lien_photo_joueur_burkina_faso"),
    Country(
        rang: 7,
        name: "Tunisie",
        countryCode: "TN",
        description: "1er du groupe J",
        dateQualification: "28 mars 2023",
        nbParticipation: 21,
        results: [2004],
        lastParticipation: "2021 (1/4 finale)",
        flag: "lien_drapeau_tunisie",
        topPlayer: "lien_photo_joueur_tunisie"),
    Country(
        rang: 8,
        name: "Égypte",
        countryCode: "EG",
        description: "1er du groupe D",
        dateQualification: "14 juin 2023",
        nbParticipation: 26,
        results: [1957, 1959, 1986, 1998, 2006, 2008, 2010],
        lastParticipation: "2021 (Finaliste)",
        flag: "lien_drapeau_egypte",
        topPlayer: "lien_photo_joueur_egypte"),
    Country(
        rang: 9,
        name: "Zambie",
        countryCode: "ZM",
        description: "1er du groupe H",
        dateQualification: "17 juin 2023",
        nbParticipation: 18,
        results: [2012],
        lastParticipation: "2015 (1er tour)",
        flag: "lien_drapeau_zambie",
        topPlayer: "lien_photo_joueur_zambie"),
    Country(
        rang: 10,
        name: "Guinée équatoriale",
        countryCode: "GQ",
        description: "2e du groupe J",
        dateQualification: "17 juin 2023",
        nbParticipation: 4,
        results: [],
        lastParticipation: "2021 (1/4 finale)",
        flag: "lien_drapeau_guinee_equatoriale",
        topPlayer: "lien_photo_joueur_guinee_equatoriale"),
    Country(
        rang: 11,
        name: "Nigeria",
        countryCode: "NG",
        description: "1er du groupe A",
        dateQualification: "18 juin 2023",
        nbParticipation: 20,
        results: [1980, 1994, 2013],
        lastParticipation: "2021 (1/8 finale)",
        flag: "lien_drapeau_nigeria",
        topPlayer: "lien_photo_joueur_nigeria"),
    Country(
        rang: 12,
        name: "Guinée-Bissau",
        countryCode: "GW",
        description: "2e du groupe A",
        dateQualification: "18 juin 2023",
        nbParticipation: 4,
        results: [],
        lastParticipation: "2021 (1er tour)",
        flag: "lien_drapeau_guinee_bissau",
        topPlayer: "lien_photo_joueur_guinee_bissau"),
    Country(
        rang: 13,
        name: "Cap-Vert",
        countryCode: "CV",
        description: "2e du groupe B",
        dateQualification: "18 juin 2023",
        nbParticipation: 4,
        results: [],
        lastParticipation: "2021 (1/8 finale)",
        flag: "lien_drapeau_cap_vert",
        topPlayer: "lien_photo_joueur_cap_vert"),
    Country(
        rang: 14,
        name: "Mali",
        countryCode: "ML",
        description: "1er du groupe G",
        dateQualification: "18 juin 2023",
        nbParticipation: 13,
        results: [],
        lastParticipation: "2021 (1/8 finale)",
        flag: "lien_drapeau_mali",
        topPlayer: "lien_photo_joueur_mali"),
    Country(
        rang: 15,
        name: "Guinée",
        countryCode: "GN",
        description: "2e du groupe D",
        dateQualification: "20 juin 2023",
        nbParticipation: 14,
        results: [],
        lastParticipation: "2021 (1/8 de finale)",
        flag: "lien_drapeau_guinee",
        topPlayer: "lien_photo_joueur_guinee"),
    Country(
        rang: 16,
        name: "Ghana",
        countryCode: "GH",
        description: "1er du groupe E",
        dateQualification: "7 septembre 2023",
        nbParticipation: 24,
        results: [1963, 1965, 1978, 1982],
        lastParticipation: "2021 (1er tour)",
        flag: "lien_drapeau_ghana",
        topPlayer: "lien_photo_joueur_ghana"),
    Country(
        rang: 17,
        name: "Angola",
        countryCode: "AO",
        description: "2e du groupe E",
        dateQualification: "7 septembre 2023",
        nbParticipation: 9,
        results: [],
        lastParticipation: "2019 (1er tour)",
        flag: "lien_drapeau_angola",
        topPlayer: "lien_photo_joueur_angola"),
    Country(
        rang: 18,
        name: "Tanzanie",
        countryCode: "TZ",
        description: "2e du groupe F",
        dateQualification: "7 septembre 2023",
        nbParticipation: 3,
        results: [],
        lastParticipation: "2019 (1er tour)",
        flag: "lien_drapeau_tanzanie",
        topPlayer: "lien_photo_joueur_tanzanie"),
    Country(
        rang: 19,
        name: "Mozambique",
        countryCode: "MZ",
        description: "2e du groupe L",
        dateQualification: "9 septembre 2023",
        nbParticipation: 5,
        results: [],
        lastParticipation: "2010 (1er tour)",
        flag: "lien_drapeau_mozambique",
        topPlayer: "lien_photo_joueur_mozambique"),
    Country(
        rang: 20,
        name: "Mauritanie",
        countryCode: "MR",
        description: "2e du groupe I",
        dateQualification: "9 septembre 2023",
        nbParticipation: 3,
        results: [],
        lastParticipation: "2021 (1er tour)",
        flag: "lien_drapeau_mauritanie",
        topPlayer: "lien_photo_joueur_mauritanie"),
    Country(
        rang: 21,
        name: "RD Congo",
        countryCode: "CD",
        description: "1er du groupe I",
        dateQualification: "9 septembre 2023",
        nbParticipation: 20,
        results: [1968, 1974],
        lastParticipation: "2019 (1/8 finale)",
        flag: "lien_drapeau_rd_congo",
        topPlayer: "lien_photo_joueur_rd_congo"),
    Country(
        rang: 22,
        name: "Gambie",
        countryCode: "GM",
        description: "2e du groupe G",
        dateQualification: "10 septembre 2023",
        nbParticipation: 2,
        results: [],
        lastParticipation: "2021 (1/4 finale)",
        flag: "lien_drapeau_gambie",
        topPlayer: "lien_photo_joueur_gambie"),
    Country(
        rang: 23,
        name: "Cameroun",
        countryCode: "CM",
        description: "1er du groupe C",
        dateQualification: "12 septembre 2023",
        nbParticipation: 20,
        results: [1984, 1988, 2000, 2002, 2017],
        lastParticipation: "2021 (3è)",
        flag: "lien_drapeau_cameroun",
        topPlayer: "lien_photo_joueur_cameroun"),
    Country(
        rang: 24,
        name: "Namibie",
        countryCode: "NA",
        description: "2e du groupe C",
        dateQualification: "12 septembre 2023",
        nbParticipation: 4,
        results: [],
        lastParticipation: "2019 (1er tour)",
        flag: "lien_drapeau_namibie",
        topPlayer: "lien_photo_joueur_namibie")
  ];
}
